// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterServiceClient interface {
	// 1 request and 1 response
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// 1 request and nhiều response
	ServerStreamData(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (GreeterService_ServerStreamDataClient, error)
	// 1 response and nhiều request
	ClientStreamData(ctx context.Context, opts ...grpc.CallOption) (GreeterService_ClientStreamDataClient, error)
	// 2 chiều song song(nhiều request và nhiều response)
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (GreeterService_BidirectionalStreamClient, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.GreeterService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.GreeterService/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) ServerStreamData(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (GreeterService_ServerStreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterService_ServiceDesc.Streams[0], "/helloworld.GreeterService/ServerStreamData", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceServerStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreeterService_ServerStreamDataClient interface {
	Recv() (*ServerStreamReply, error)
	grpc.ClientStream
}

type greeterServiceServerStreamDataClient struct {
	grpc.ClientStream
}

func (x *greeterServiceServerStreamDataClient) Recv() (*ServerStreamReply, error) {
	m := new(ServerStreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) ClientStreamData(ctx context.Context, opts ...grpc.CallOption) (GreeterService_ClientStreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterService_ServiceDesc.Streams[1], "/helloworld.GreeterService/ClientStreamData", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceClientStreamDataClient{stream}
	return x, nil
}

type GreeterService_ClientStreamDataClient interface {
	Send(*ClientStreamRequest) error
	CloseAndRecv() (*ClientStreamReply, error)
	grpc.ClientStream
}

type greeterServiceClientStreamDataClient struct {
	grpc.ClientStream
}

func (x *greeterServiceClientStreamDataClient) Send(m *ClientStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterServiceClientStreamDataClient) CloseAndRecv() (*ClientStreamReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientStreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterServiceClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (GreeterService_BidirectionalStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterService_ServiceDesc.Streams[2], "/helloworld.GreeterService/BidirectionalStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceBidirectionalStreamClient{stream}
	return x, nil
}

type GreeterService_BidirectionalStreamClient interface {
	Send(*BidirectionalStreamRequest) error
	Recv() (*BidirectionalStreamReply, error)
	grpc.ClientStream
}

type greeterServiceBidirectionalStreamClient struct {
	grpc.ClientStream
}

func (x *greeterServiceBidirectionalStreamClient) Send(m *BidirectionalStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterServiceBidirectionalStreamClient) Recv() (*BidirectionalStreamReply, error) {
	m := new(BidirectionalStreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServiceServer is the server API for GreeterService service.
// All implementations must embed UnimplementedGreeterServiceServer
// for forward compatibility
type GreeterServiceServer interface {
	// 1 request and 1 response
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
	// 1 request and nhiều response
	ServerStreamData(*ServerStreamRequest, GreeterService_ServerStreamDataServer) error
	// 1 response and nhiều request
	ClientStreamData(GreeterService_ClientStreamDataServer) error
	// 2 chiều song song(nhiều request và nhiều response)
	BidirectionalStream(GreeterService_BidirectionalStreamServer) error
	mustEmbedUnimplementedGreeterServiceServer()
}

// UnimplementedGreeterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServiceServer struct {
}

func (UnimplementedGreeterServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServiceServer) SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgain not implemented")
}
func (UnimplementedGreeterServiceServer) ServerStreamData(*ServerStreamRequest, GreeterService_ServerStreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamData not implemented")
}
func (UnimplementedGreeterServiceServer) ClientStreamData(GreeterService_ClientStreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamData not implemented")
}
func (UnimplementedGreeterServiceServer) BidirectionalStream(GreeterService_BidirectionalStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedGreeterServiceServer) mustEmbedUnimplementedGreeterServiceServer() {}

// UnsafeGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServiceServer will
// result in compilation errors.
type UnsafeGreeterServiceServer interface {
	mustEmbedUnimplementedGreeterServiceServer()
}

func RegisterGreeterServiceServer(s grpc.ServiceRegistrar, srv GreeterServiceServer) {
	s.RegisterService(&GreeterService_ServiceDesc, srv)
}

func _GreeterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.GreeterService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.GreeterService/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_ServerStreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).ServerStreamData(m, &greeterServiceServerStreamDataServer{stream})
}

type GreeterService_ServerStreamDataServer interface {
	Send(*ServerStreamReply) error
	grpc.ServerStream
}

type greeterServiceServerStreamDataServer struct {
	grpc.ServerStream
}

func (x *greeterServiceServerStreamDataServer) Send(m *ServerStreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GreeterService_ClientStreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServiceServer).ClientStreamData(&greeterServiceClientStreamDataServer{stream})
}

type GreeterService_ClientStreamDataServer interface {
	SendAndClose(*ClientStreamReply) error
	Recv() (*ClientStreamRequest, error)
	grpc.ServerStream
}

type greeterServiceClientStreamDataServer struct {
	grpc.ServerStream
}

func (x *greeterServiceClientStreamDataServer) SendAndClose(m *ClientStreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterServiceClientStreamDataServer) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreeterService_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServiceServer).BidirectionalStream(&greeterServiceBidirectionalStreamServer{stream})
}

type GreeterService_BidirectionalStreamServer interface {
	Send(*BidirectionalStreamReply) error
	Recv() (*BidirectionalStreamRequest, error)
	grpc.ServerStream
}

type greeterServiceBidirectionalStreamServer struct {
	grpc.ServerStream
}

func (x *greeterServiceBidirectionalStreamServer) Send(m *BidirectionalStreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterServiceBidirectionalStreamServer) Recv() (*BidirectionalStreamRequest, error) {
	m := new(BidirectionalStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterService_ServiceDesc is the grpc.ServiceDesc for GreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreeterService_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _GreeterService_SayHelloAgain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamData",
			Handler:       _GreeterService_ServerStreamData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamData",
			Handler:       _GreeterService_ClientStreamData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _GreeterService_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
