version: "3"

services:
  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dinhpv
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    ports:
      - 27017:27017
    volumes:
      - ./init-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./data:/data/db
